/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'GeoStyler Beginner Tutorial',
      link: {type: 'doc', id: 'beginner-workshop/README'},
      items: [
        'beginner-workshop/introduction/README',
        {
          type: 'category',
          label: 'First Steps',
          link: {type: 'doc', id: 'beginner-workshop/first-steps/README'},
          items: ['beginner-workshop/first-steps/create-react-app', 'beginner-workshop/first-steps/install-geostyler'],
        },
        {
          type: 'category',
          label: 'Style Parsers',
          link: {type: 'doc', id: 'beginner-workshop/style-parser/README'},
          items: ['beginner-workshop/style-parser/parse-sld', 'beginner-workshop/style-parser/parse-ol', 'beginner-workshop/style-parser/convert'],
        },
        {
          type: 'category',
          label: 'Using UI Components',
          link: {type: 'doc', id: 'beginner-workshop/edit-ui/README'},
          items: ['beginner-workshop/edit-ui/geostyler-component', 'beginner-workshop/edit-ui/preview', 'beginner-workshop/edit-ui/parser-to-ui'],
        },
        {
          type: 'category',
          label: 'Data Parsers',
          link: {type: 'doc', id: 'beginner-workshop/data-parser/README'},
          items: ['beginner-workshop/data-parser/parse-wfs', 'beginner-workshop/data-parser/parser-to-ui'],
        },
        'beginner-workshop/summary/summary'
      ]
    },
  ],
   
};

module.exports = sidebars;
